import { useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    const cursorElement = document.querySelector(".cursor");
    const pressedCursorElement = document.querySelector(".cursor-sm");

    const moveCursor = (e) => {
      const mouseY = e.clientY;
      const mouseX = e.clientX;
      cursorElement.style.transform = `translate3d(${mouseX}px, ${mouseY}px, 0)`;
      pressedCursorElement.style.transform = `translate3d(${mouseX}px, ${mouseY}px, 0)`;
    };

    const mousePress = (e) => {
      const mouseY = e.clientY;
      const mouseX = e.clientX;

      var audio = new Audio("plop.wav");
      audio.play();

      cursorElement.style.display = "none";
      pressedCursorElement.style.display = "block";
      drawCircle(mouseX, mouseY);
    };

    const mouseUp = () => {
      cursorElement.style.display = "block";
      pressedCursorElement.style.display = "none";
    };

    const drawCircle = (x, y) => {
      const randomColor = Math.floor(Math.random() * 16777215).toString(16);
      const newCircle = document.createElement("img");
      newCircle.src = "finger.svg";
      newCircle.style.cssText = `position:absolute;top:${y}px;left:${x}px;width:65px;height:65px;border-radius:65px;fill:#${randomColor};`;
      document.body.appendChild(newCircle);
    };

    window.addEventListener("mousemove", moveCursor);
    window.addEventListener("mousedown", mousePress);
    window.addEventListener("mouseup", mouseUp);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Mikey G</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="thumb.png" className="cursor" />
        <img src="thumb.png" className="cursor-sm" />
      </main>
    </div>
  );
}
